[build]
  command = "./run.sh build:prod"
  functions = "functions"
  publish = "dist"

[build.environment]
  GO_IMPORT_PATH = "github.com/spotlightpa/almanack"
  GO111MODULE = "on"
  NODE_VERSION = "16"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/almanack-api/:splat"
  force = true
  status = 200

[[redirects]]
  from = "/api-background/*"
  to = "/.netlify/functions/almanack-api-background/:splat"
  force = true
  status = 200

[[redirects]]
  from = "/ssr/*"
  to = "/.netlify/functions/almanack-api/:splat"
  conditions = { Role = ["admin"]}
  force = true
  status = 200

[[redirects]]
  from = "/ssr/*"
  to = "/.netlify/functions/almanack-api/:splat"
  conditions = { Role = ["Spotlight PA"]}
  force = true
  status = 200

[[redirects]]
  from = "/ssr/*"
  to = "/.netlify/functions/almanack-api/:splat"
  conditions = { Role = ["editor"]}
  force = true
  status = 200

[[redirects]]
  from = "/ssr/*"
  to = "/login"
  force = true
  status = 302

[[redirects]]
  from = "/login"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/admin/*"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/articles/*"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/shared-articles/*"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404
  force = false
