import Vue from "vue";

import ArcArticleAvailable from "@/components/ArcArticleAvailable.vue";
Vue.component("ArcArticleAvailable", ArcArticleAvailable);
import AdminList from "@/components/AdminList.vue";
Vue.component("AdminList", AdminList);
import AdminListPanel from "@/components/AdminListPanel.vue";
Vue.component("AdminListPanel", AdminListPanel);
import APILoader from "@/components/APILoader.vue";
Vue.component("APILoader", APILoader);
import AppNav from "@/components/AppNav.vue";
Vue.component("AppNav", AppNav);
import ArcArticleDivider from "@/components/ArcArticleDivider.vue";
Vue.component("ArcArticleDivider", ArcArticleDivider);
import ArcArticleHeader from "@/components/ArcArticleHeader.vue";
Vue.component("ArcArticleHeader", ArcArticleHeader);
import ArcArticleHTML from "@/components/ArcArticleHTML.vue";
Vue.component("ArcArticleHTML", ArcArticleHTML);
import ArcArticleImage from "@/components/ArcArticleImage.vue";
Vue.component("ArcArticleImage", ArcArticleImage);
import ArcArticleList from "@/components/ArcArticleList.vue";
Vue.component("ArcArticleList", ArcArticleList);
import ArcArticleOEmbed from "@/components/ArcArticleOEmbed.vue";
Vue.component("ArcArticleOEmbed", ArcArticleOEmbed);
import ArcArticlePlaceholder from "@/components/ArcArticlePlaceholder.vue";
Vue.component("ArcArticlePlaceholder", ArcArticlePlaceholder);
import ArcArticlePlanned from "@/components/ArcArticlePlanned.vue";
Vue.component("ArcArticlePlanned", ArcArticlePlanned);
import ArcArticleText from "@/components/ArcArticleText.vue";
Vue.component("ArcArticleText", ArcArticleText);
import ArticleList from "@/components/ArticleList.vue";
Vue.component("ArticleList", ArticleList);
import ArticleSlugLine from "@/components/ArticleSlugLine.vue";
Vue.component("ArticleSlugLine", ArticleSlugLine);
import ArticleWordCount from "@/components/ArticleWordCount.vue";
Vue.component("ArticleWordCount", ArticleWordCount);
import BulmaAutocompleteArray from "@/components/BulmaAutocompleteArray.vue";
Vue.component("BulmaAutocompleteArray", BulmaAutocompleteArray);
import BulmaBreadcrumbs from "@/components/BulmaBreadcrumbs.vue";
Vue.component("BulmaBreadcrumbs", BulmaBreadcrumbs);
import BulmaField from "@/components/BulmaField.vue";
Vue.component("BulmaField", BulmaField);
import BulmaFieldInput from "@/components/BulmaFieldInput.vue";
Vue.component("BulmaFieldInput", BulmaFieldInput);
import CopyTextarea from "@/components/CopyTextarea.vue";
Vue.component("CopyTextarea", CopyTextarea);
import CopyWithButton from "@/components/CopyWithButton.vue";
Vue.component("CopyWithButton", CopyWithButton);
import DOMInnerHTML from "@/components/DOMInnerHTML.vue";
Vue.component("DOMInnerHTML", DOMInnerHTML);
import EditorsPicks from "@/components/EditorsPicks.vue";
Vue.component("EditorsPicks", EditorsPicks);
import EditorsPicksDraggable from "@/components/EditorsPicksDraggable.vue";
Vue.component("EditorsPicksDraggable", EditorsPicksDraggable);
import EmailComposer from "@/components/EmailComposer.vue";
Vue.component("EmailComposer", EmailComposer);
import ErrorSimple from "@/components/ErrorSimple.vue";
Vue.component("ErrorSimple", ErrorSimple);
import ErrorReloader from "@/components/ErrorReloader.vue";
Vue.component("ErrorReloader", ErrorReloader);
import ImageThumbnail from "@/components/ImageThumbnail.vue";
Vue.component("ImageThumbnail", ImageThumbnail);
import ImageUploader from "@/components/ImageUploader.vue";
Vue.component("ImageUploader", ImageUploader);
import NoCopyTextArea from "@/components/NoCopyTextArea.vue";
Vue.component("NoCopyTextArea", NoCopyTextArea);
import PageListRow from "@/components/PageListRow.vue";
Vue.component("PageListRow", PageListRow);
import PickerFiles from "@/components/PickerFiles.vue";
Vue.component("PickerFiles", PickerFiles);
import PickerImages from "@/components/PickerImages.vue";
Vue.component("PickerImages", PickerImages);
import SiteParams from "@/components/SiteParams.vue";
Vue.component("SiteParams", SiteParams);
import SiteParamsFiles from "@/components/SiteParamsFiles.vue";
Vue.component("SiteParamsFiles", SiteParamsFiles);
import SpinnerProgress from "@/components/SpinnerProgress.vue";
Vue.component("SpinnerProgress", SpinnerProgress);
import TagDate from "@/components/TagDate.vue";
Vue.component("TagDate", TagDate);
import TagStatus from "@/components/TagStatus.vue";
Vue.component("TagStatus", TagStatus);
import TheApp from "@/components/TheApp.vue";
Vue.component("TheApp", TheApp);
import ViewAdmin from "@/components/ViewAdmin.vue";
Vue.component("ViewAdmin", ViewAdmin);
import ViewArcArticle from "@/components/ViewArcArticle.vue";
Vue.component("ViewArcArticle", ViewArcArticle);
import ViewAuthorizedDomains from "@/components/ViewAuthorizedDomains.vue";
Vue.component("ViewAuthorizedDomains", ViewAuthorizedDomains);
import ViewEditorsPicks from "@/components/ViewEditorsPicks.vue";
Vue.component("ViewEditorsPicks", ViewEditorsPicks);
import ViewError from "@/components/ViewError.vue";
Vue.component("ViewError", ViewError);
import ViewFileUploader from "@/components/ViewFileUploader.vue";
Vue.component("ViewFileUploader", ViewFileUploader);
import ViewLogin from "@/components/ViewLogin.vue";
Vue.component("ViewLogin", ViewLogin);
import ViewNewsletterList from "@/components/ViewNewsletterList.vue";
Vue.component("ViewNewsletterList", ViewNewsletterList);
import ViewNewsletterPage from "@/components/ViewNewsletterPage.vue";
Vue.component("ViewNewsletterPage", ViewNewsletterPage);
import ViewNewsPage from "@/components/ViewNewsPage.vue";
Vue.component("ViewNewsPage", ViewNewsPage);
import ViewNewsPagesList from "@/components/ViewNewsPagesList.vue";
Vue.component("ViewNewsPagesList", ViewNewsPagesList);
import ViewRedirectArcToNewsPage from "@/components/ViewRedirectArcToNewsPage.vue";
Vue.component("ViewRedirectArcToNewsPage", ViewRedirectArcToNewsPage);
import ViewSharedList from "@/components/ViewSharedList.vue";
Vue.component("ViewSharedList", ViewSharedList);
import ViewSiteParams from "@/components/ViewSiteParams.vue";
Vue.component("ViewSiteParams", ViewSiteParams);
import ViewUnauthorized from "@/components/ViewUnauthorized.vue";
Vue.component("ViewUnauthorized", ViewUnauthorized);
import ViewUploader from "@/components/ViewUploader.vue";
Vue.component("ViewUploader", ViewUploader);
