// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: apple-news-channel.sql

package db

import (
	"context"
)

const createAppleNewsChannel = `-- name: CreateAppleNewsChannel :one
INSERT INTO apple_news_channel (name, channel_id, KEY, secret, feed_url, active)
  VALUES ($1, $2, $3, $4, $5, $6)
RETURNING
  id, name, channel_id, key, secret, feed_url, active, last_synced_at, created_at, updated_at
`

type CreateAppleNewsChannelParams struct {
	Name      string `json:"name"`
	ChannelID string `json:"channel_id"`
	Key       string `json:"key"`
	Secret    string `json:"secret"`
	FeedUrl   string `json:"feed_url"`
	Active    bool   `json:"active"`
}

func (q *Queries) CreateAppleNewsChannel(ctx context.Context, arg CreateAppleNewsChannelParams) (AppleNewsChannel, error) {
	row := q.db.QueryRow(ctx, createAppleNewsChannel,
		arg.Name,
		arg.ChannelID,
		arg.Key,
		arg.Secret,
		arg.FeedUrl,
		arg.Active,
	)
	var i AppleNewsChannel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ChannelID,
		&i.Key,
		&i.Secret,
		&i.FeedUrl,
		&i.Active,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAppleNewsChannelWithID = `-- name: CreateAppleNewsChannelWithID :one
INSERT INTO apple_news_channel (id, name, channel_id, KEY, secret, feed_url, active)
  VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING
  id, name, channel_id, key, secret, feed_url, active, last_synced_at, created_at, updated_at
`

type CreateAppleNewsChannelWithIDParams struct {
	ID        int64  `json:"id"`
	Name      string `json:"name"`
	ChannelID string `json:"channel_id"`
	Key       string `json:"key"`
	Secret    string `json:"secret"`
	FeedUrl   string `json:"feed_url"`
	Active    bool   `json:"active"`
}

func (q *Queries) CreateAppleNewsChannelWithID(ctx context.Context, arg CreateAppleNewsChannelWithIDParams) (AppleNewsChannel, error) {
	row := q.db.QueryRow(ctx, createAppleNewsChannelWithID,
		arg.ID,
		arg.Name,
		arg.ChannelID,
		arg.Key,
		arg.Secret,
		arg.FeedUrl,
		arg.Active,
	)
	var i AppleNewsChannel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ChannelID,
		&i.Key,
		&i.Secret,
		&i.FeedUrl,
		&i.Active,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAppleNewsChannel = `-- name: DeleteAppleNewsChannel :exec
DELETE FROM apple_news_channel
WHERE id = $1
`

func (q *Queries) DeleteAppleNewsChannel(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteAppleNewsChannel, id)
	return err
}

const getAppleNewsChannel = `-- name: GetAppleNewsChannel :one
SELECT
  id, name, channel_id, key, secret, feed_url, active, last_synced_at, created_at, updated_at
FROM
  apple_news_channel
WHERE
  id = $1
`

func (q *Queries) GetAppleNewsChannel(ctx context.Context, id int64) (AppleNewsChannel, error) {
	row := q.db.QueryRow(ctx, getAppleNewsChannel, id)
	var i AppleNewsChannel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ChannelID,
		&i.Key,
		&i.Secret,
		&i.FeedUrl,
		&i.Active,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveAppleNewsChannels = `-- name: ListActiveAppleNewsChannels :many
SELECT
  id, name, channel_id, key, secret, feed_url, active, last_synced_at, created_at, updated_at
FROM
  apple_news_channel
WHERE
  active = TRUE
ORDER BY
  name
`

func (q *Queries) ListActiveAppleNewsChannels(ctx context.Context) ([]AppleNewsChannel, error) {
	rows, err := q.db.Query(ctx, listActiveAppleNewsChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppleNewsChannel
	for rows.Next() {
		var i AppleNewsChannel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ChannelID,
			&i.Key,
			&i.Secret,
			&i.FeedUrl,
			&i.Active,
			&i.LastSyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppleNewsChannels = `-- name: ListAppleNewsChannels :many
SELECT
  id, name, channel_id, key, secret, feed_url, active, last_synced_at, created_at, updated_at
FROM
  apple_news_channel
ORDER BY
  name
`

func (q *Queries) ListAppleNewsChannels(ctx context.Context) ([]AppleNewsChannel, error) {
	rows, err := q.db.Query(ctx, listAppleNewsChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppleNewsChannel
	for rows.Next() {
		var i AppleNewsChannel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ChannelID,
			&i.Key,
			&i.Secret,
			&i.FeedUrl,
			&i.Active,
			&i.LastSyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAppleNewsChannel = `-- name: UpdateAppleNewsChannel :one
UPDATE
  apple_news_channel
SET
  name = $1,
  channel_id = $2,
  KEY = $3,
  secret = $4,
  feed_url = $5,
  active = $6,
  updated_at = CURRENT_TIMESTAMP
WHERE
  id = $7
RETURNING
  id, name, channel_id, key, secret, feed_url, active, last_synced_at, created_at, updated_at
`

type UpdateAppleNewsChannelParams struct {
	Name      string `json:"name"`
	ChannelID string `json:"channel_id"`
	Key       string `json:"key"`
	Secret    string `json:"secret"`
	FeedUrl   string `json:"feed_url"`
	Active    bool   `json:"active"`
	ID        int64  `json:"id"`
}

func (q *Queries) UpdateAppleNewsChannel(ctx context.Context, arg UpdateAppleNewsChannelParams) (AppleNewsChannel, error) {
	row := q.db.QueryRow(ctx, updateAppleNewsChannel,
		arg.Name,
		arg.ChannelID,
		arg.Key,
		arg.Secret,
		arg.FeedUrl,
		arg.Active,
		arg.ID,
	)
	var i AppleNewsChannel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ChannelID,
		&i.Key,
		&i.Secret,
		&i.FeedUrl,
		&i.Active,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAppleNewsChannelLastSynced = `-- name: UpdateAppleNewsChannelLastSynced :exec
UPDATE
  apple_news_channel
SET
  last_synced_at = CURRENT_TIMESTAMP,
  updated_at = CURRENT_TIMESTAMP
WHERE
  id = $1
`

func (q *Queries) UpdateAppleNewsChannelLastSynced(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, updateAppleNewsChannelLastSynced, id)
	return err
}
