// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: arc.sql

package db

import (
	"context"
)

const getArcByArcID = `-- name: GetArcByArcID :one
SELECT
  id, arc_id, raw_data, last_updated, created_at, updated_at
FROM
  arc
WHERE
  arc_id = $1
`

func (q *Queries) GetArcByArcID(ctx context.Context, arcID string) (Arc, error) {
	row := q.db.QueryRow(ctx, getArcByArcID, arcID)
	var i Arc
	err := row.Scan(
		&i.ID,
		&i.ArcID,
		&i.RawData,
		&i.LastUpdated,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
