// Code generated by sqlc. DO NOT EDIT.
// source: domain-roles.sql

package db

import (
	"context"

	"github.com/lib/pq"
)

const getRolesForDomain = `-- name: GetRolesForDomain :one
SELECT
    roles
FROM
    domain_roles
WHERE
    DOMAIN LIKE $1
`

func (q *Queries) GetRolesForDomain(ctx context.Context, domain string) ([]string, error) {
	row := q.db.QueryRowContext(ctx, getRolesForDomain, domain)
	var roles []string
	err := row.Scan(pq.Array(&roles))
	return roles, err
}
