// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: gdocs.sql

package db

import (
	"context"
)

const listGDocsWhereUnprocessed = `-- name: ListGDocsWhereUnprocessed :many
SELECT
  id, g_docs_id, document, embeds, rich_text, raw_html, article_markdown, word_count, processed_at, created_at
FROM
  g_docs_doc
WHERE
  processed_at IS NULL
`

func (q *Queries) ListGDocsWhereUnprocessed(ctx context.Context) ([]GDocsDoc, error) {
	rows, err := q.db.Query(ctx, listGDocsWhereUnprocessed)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GDocsDoc
	for rows.Next() {
		var i GDocsDoc
		if err := rows.Scan(
			&i.ID,
			&i.GDocsID,
			&i.Document,
			&i.Embeds,
			&i.RichText,
			&i.RawHtml,
			&i.ArticleMarkdown,
			&i.WordCount,
			&i.ProcessedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
