// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"time"
)

type DomainRole struct {
	ID        int32     `json:"id"`
	Domain    string    `json:"domain"`
	Roles     []string  `json:"roles"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
