// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: news-feed.sql

package db

import (
	"context"
)

const updateANFArchives = `-- name: UpdateANFArchives :execrows
WITH raw_json AS (
  SELECT
    jsonb_array_elements($1::jsonb) AS data
),
feed_items AS (
  SELECT
    data ->> 'id' AS external_id,
    data ->> 'author' AS author,
    CASE WHEN data ? 'authors' THEN
      ARRAY (
        SELECT
          jsonb_array_elements_text(data -> 'authors'))
      ELSE
        '{}'::text[]
    END AS authors,
    data ->> 'category' AS category,
    data ->> 'content_html' AS content_html,
    iso_to_timestamptz (data ->> 'date_modified')::timestamptz AS external_updated_at,
    iso_to_timestamptz (data ->> 'date_published')::timestamptz AS external_published_at,
    data ->> 'image' AS image,
    data ->> 'image_credit' AS image_credit,
    data ->> 'image_description' AS image_description,
    data ->> 'language' AS "language",
    data ->> 'title' AS title,
    data ->> 'url' AS url
  FROM
    raw_json)
  INSERT INTO apple_news_feed ("external_id", "author", "authors", "category",
    "content_html", "external_updated_at", "external_published_at", "image",
    "image_credit", "image_description", "language", "title", "url")
  SELECT
    "external_id",
    COALESCE("author", ''),
    "authors",
    COALESCE("category", ''),
    COALESCE("content_html", ''),
    "external_updated_at",
    "external_published_at",
    COALESCE("image", ''),
    COALESCE("image_credit", ''),
    COALESCE("image_description", ''),
    COALESCE("language", ''),
    COALESCE("title", ''),
    COALESCE("url", '')
  FROM
    feed_items
  ON CONFLICT ("external_id")
    DO UPDATE SET
      "author" = EXCLUDED.author,
      "authors" = EXCLUDED.authors,
      "category" = EXCLUDED.category,
      "content_html" = EXCLUDED.content_html,
      "external_updated_at" = EXCLUDED.external_updated_at,
      "external_published_at" = EXCLUDED.external_published_at,
      "image" = EXCLUDED.image,
      "image_credit" = EXCLUDED.image_credit,
      "image_description" = EXCLUDED.image_description,
      "language" = EXCLUDED.language,
      "title" = EXCLUDED.title,
      "url" = EXCLUDED.url,
      "uploaded_at" = NULL,
      "updated_at" = CURRENT_TIMESTAMP
`

func (q *Queries) UpdateANFArchives(ctx context.Context, data []byte) (int64, error) {
	result, err := q.db.Exec(ctx, updateANFArchives, data)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
