// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: promotion.sql

package db

import (
	"context"
)

const createPromotion = `-- name: CreatePromotion :one
INSERT INTO "promotion" ("name", "description", "link", "width", "height", "image_urls")
  VALUES ($1, $2, $3, $4, $5, $6)
RETURNING
  id, name, description, link, width, height, image_urls, created_at, updated_at
`

type CreatePromotionParams struct {
	Name        string   `json:"name"`
	Description string   `json:"description"`
	Link        string   `json:"link"`
	Width       int32    `json:"width"`
	Height      int32    `json:"height"`
	ImageUrls   []string `json:"image_urls"`
}

func (q *Queries) CreatePromotion(ctx context.Context, arg CreatePromotionParams) (Promotion, error) {
	row := q.db.QueryRow(ctx, createPromotion,
		arg.Name,
		arg.Description,
		arg.Link,
		arg.Width,
		arg.Height,
		arg.ImageUrls,
	)
	var i Promotion
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Link,
		&i.Width,
		&i.Height,
		&i.ImageUrls,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePromotion = `-- name: DeletePromotion :execrows
DELETE FROM "promotion"
WHERE "id" = $1
`

func (q *Queries) DeletePromotion(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deletePromotion, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listPromotionByFTS = `-- name: ListPromotionByFTS :many
WITH tsq AS (
  SELECT
    websearch_to_tsquery('english', $5::text) AS q
)
SELECT
  promotion.id, promotion.name, promotion.description, promotion.link, promotion.width, promotion.height, promotion.image_urls, promotion.created_at, promotion.updated_at
FROM
  "promotion"
  INNER JOIN tsq ON fts_doc_en @@ tsq.q
WHERE ("promotion"."width" = $3
  OR "promotion"."width" = 0
  OR $3 = 0)
AND ("promotion"."height" = $4
  OR "promotion"."height" = 0
  OR $4 = 0)
ORDER BY
  ts_rank(fts_doc_en, tsq.q) DESC
LIMIT $1 OFFSET $2
`

type ListPromotionByFTSParams struct {
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
	Width  int32  `json:"width"`
	Height int32  `json:"height"`
	Text   string `json:"text"`
}

func (q *Queries) ListPromotionByFTS(ctx context.Context, arg ListPromotionByFTSParams) ([]Promotion, error) {
	rows, err := q.db.Query(ctx, listPromotionByFTS,
		arg.Limit,
		arg.Offset,
		arg.Width,
		arg.Height,
		arg.Text,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Promotion
	for rows.Next() {
		var i Promotion
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Link,
			&i.Width,
			&i.Height,
			&i.ImageUrls,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPromotionByUpdated = `-- name: ListPromotionByUpdated :many
SELECT
  id, name, description, link, width, height, image_urls, created_at, updated_at
FROM
  "promotion"
WHERE ("promotion"."width" = $3
  OR "promotion"."width" = 0
  OR $3 = 0)
AND ("promotion"."height" = $4
  OR "promotion"."height" = 0
  OR $4 = 0)
ORDER BY
  "updated_at" DESC
LIMIT $1 OFFSET $2
`

type ListPromotionByUpdatedParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
	Width  int32 `json:"width"`
	Height int32 `json:"height"`
}

func (q *Queries) ListPromotionByUpdated(ctx context.Context, arg ListPromotionByUpdatedParams) ([]Promotion, error) {
	rows, err := q.db.Query(ctx, listPromotionByUpdated,
		arg.Limit,
		arg.Offset,
		arg.Width,
		arg.Height,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Promotion
	for rows.Next() {
		var i Promotion
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Link,
			&i.Width,
			&i.Height,
			&i.ImageUrls,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePromotion = `-- name: UpdatePromotion :one
UPDATE
  "promotion"
SET
  "name" = $1,
  "description" = $2,
  "link" = $3,
  "width" = $4,
  "height" = $5,
  "image_urls" = $6,
  "updated_at" = CURRENT_TIMESTAMP
WHERE
  "id" = $7
RETURNING
  id, name, description, link, width, height, image_urls, created_at, updated_at
`

type UpdatePromotionParams struct {
	Name        string   `json:"name"`
	Description string   `json:"description"`
	Link        string   `json:"link"`
	Width       int32    `json:"width"`
	Height      int32    `json:"height"`
	ImageUrls   []string `json:"image_urls"`
	ID          int64    `json:"id"`
}

func (q *Queries) UpdatePromotion(ctx context.Context, arg UpdatePromotionParams) (Promotion, error) {
	row := q.db.QueryRow(ctx, updatePromotion,
		arg.Name,
		arg.Description,
		arg.Link,
		arg.Width,
		arg.Height,
		arg.ImageUrls,
		arg.ID,
	)
	var i Promotion
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Link,
		&i.Width,
		&i.Height,
		&i.ImageUrls,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
