// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: redirect.sql

package db

import (
	"context"
)

const getRedirect = `-- name: GetRedirect :one
SELECT
  id, "from", "to", roles, code, created_at
FROM
  "redirect"
WHERE
  "from" = $1
`

func (q *Queries) GetRedirect(ctx context.Context, from string) (Redirect, error) {
	row := q.db.QueryRow(ctx, getRedirect, from)
	var i Redirect
	err := row.Scan(
		&i.ID,
		&i.From,
		&i.To,
		&i.Roles,
		&i.Code,
		&i.CreatedAt,
	)
	return i, err
}
