// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: youtube.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listYouTubeWhereNoPage = `-- name: ListYouTubeWhereNoPage :many
SELECT
  id, external_id, title, url, thumbnail_url, external_published_at, external_updated_at, created_at, updated_at, page_id
FROM
  youtube
WHERE
  "page_id" IS NULL
`

func (q *Queries) ListYouTubeWhereNoPage(ctx context.Context) ([]Youtube, error) {
	rows, err := q.db.Query(ctx, listYouTubeWhereNoPage)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Youtube
	for rows.Next() {
		var i Youtube
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.Title,
			&i.URL,
			&i.ThumbnailUrl,
			&i.ExternalPublishedAt,
			&i.ExternalUpdatedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listYouTubeWhereRegular = `-- name: ListYouTubeWhereRegular :many
SELECT
  id, external_id, title, url, thumbnail_url, external_published_at, external_updated_at, created_at, updated_at, page_id
FROM
  youtube
WHERE
  "url" LIKE '%/watch?v=%'
ORDER BY
  "external_published_at" DESC
LIMIT $1 OFFSET $2
`

type ListYouTubeWhereRegularParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListYouTubeWhereRegular(ctx context.Context, arg ListYouTubeWhereRegularParams) ([]Youtube, error) {
	rows, err := q.db.Query(ctx, listYouTubeWhereRegular, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Youtube
	for rows.Next() {
		var i Youtube
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.Title,
			&i.URL,
			&i.ThumbnailUrl,
			&i.ExternalPublishedAt,
			&i.ExternalUpdatedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listYouTubeWhereShort = `-- name: ListYouTubeWhereShort :many
SELECT
  id, external_id, title, url, thumbnail_url, external_published_at, external_updated_at, created_at, updated_at, page_id
FROM
  youtube
WHERE
  "url" LIKE '%/shorts/%'
ORDER BY
  "external_published_at" DESC
LIMIT $1 OFFSET $2
`

type ListYouTubeWhereShortParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListYouTubeWhereShort(ctx context.Context, arg ListYouTubeWhereShortParams) ([]Youtube, error) {
	rows, err := q.db.Query(ctx, listYouTubeWhereShort, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Youtube
	for rows.Next() {
		var i Youtube
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.Title,
			&i.URL,
			&i.ThumbnailUrl,
			&i.ExternalPublishedAt,
			&i.ExternalUpdatedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetYouTubeMaxID = `-- name: ResetYouTubeMaxID :exec
SELECT
  setval('youtube_id_seq', (
      SELECT
        MAX(id)
      FROM youtube))
`

func (q *Queries) ResetYouTubeMaxID(ctx context.Context) error {
	_, err := q.db.Exec(ctx, resetYouTubeMaxID)
	return err
}

const updateYouTubePage = `-- name: UpdateYouTubePage :one
UPDATE
  youtube
SET
  "page_id" = $1,
  "updated_at" = CURRENT_TIMESTAMP
WHERE
  "id" = $2
RETURNING
  id, external_id, title, url, thumbnail_url, external_published_at, external_updated_at, created_at, updated_at, page_id
`

type UpdateYouTubePageParams struct {
	PageID pgtype.Int8 `json:"page_id"`
	ID     int64       `json:"id"`
}

func (q *Queries) UpdateYouTubePage(ctx context.Context, arg UpdateYouTubePageParams) (Youtube, error) {
	row := q.db.QueryRow(ctx, updateYouTubePage, arg.PageID, arg.ID)
	var i Youtube
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Title,
		&i.URL,
		&i.ThumbnailUrl,
		&i.ExternalPublishedAt,
		&i.ExternalUpdatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PageID,
	)
	return i, err
}

const upsertYouTubeFeedArchives = `-- name: UpsertYouTubeFeedArchives :execrows
WITH raw_json AS (
  SELECT
    jsonb_array_elements($1::jsonb) AS data
),
feed_items AS (
  SELECT
    data ->> 'external_id' AS "external_id",
    data ->> 'title' AS "title",
    data ->> 'url' AS url,
    data ->> 'thumbnail_url' AS "thumbnail_url",
    iso_to_timestamptz (data ->> 'external_updated_at')::timestamptz AS "external_updated_at",
    iso_to_timestamptz (data ->> 'external_published_at')::timestamptz AS "external_published_at"
  FROM
    raw_json)
INSERT INTO youtube ("external_id", "title", "url", "thumbnail_url",
  "external_published_at", "external_updated_at")
SELECT
  "external_id",
  "title",
  "url",
  "thumbnail_url",
  "external_published_at",
  "external_updated_at"
FROM
  feed_items
ON CONFLICT ("external_id")
  DO UPDATE SET
    "title" = EXCLUDED.title,
    "url" = EXCLUDED.url,
    "thumbnail_url" = EXCLUDED.thumbnail_url,
    "external_published_at" = EXCLUDED.external_published_at,
    "external_updated_at" = EXCLUDED.external_updated_at,
    "uploaded_at" = CASE WHEN youtube.external_updated_at <>
      EXCLUDED.external_updated_at THEN
      NULL
    ELSE
      youtube.uploaded_at
    END,
    "updated_at" = CURRENT_TIMESTAMP
`

func (q *Queries) UpsertYouTubeFeedArchives(ctx context.Context, data []byte) (int64, error) {
	result, err := q.db.Exec(ctx, upsertYouTubeFeedArchives, data)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
