env:
  GO_VERSION: 1.18

on:
  workflow_dispatch:
  schedule:
    - cron: "0 17 1 * *" # 1st of the month at 8am EDT

jobs:
  dep_update:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Update minor and patch-level dependencies
        run: go get -t -u ./...

      - name: Tidy
        run: go mod tidy

      - name: Create pull request
        uses: peter-evans/create-pull-request@v4
        with:
          title: "Update package dependencies + tidy"
          body: Update package dependencies + tidy
          branch: "deps/update"
          commit-message: Update package dependencies + tidy
          author: "Bot <actions@users.noreply.github.com>"
          committer: "Bot <actions@users.noreply.github.com>"
          delete-branch: true
