name: Go
on: [push]
permissions:
  contents: read
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "stable"
      - name: Download modules
        run: go mod download
      - name: Check go.mod
        run: go mod tidy -diff
      - name: Test
        run: ./run.sh test:backend
        env:
          ALMANACK_POSTGRES: postgres://postgres:postgres@localhost:5432/postgres?sslmode=disable
          PG_LOCAL_URL: postgres://postgres:postgres@localhost:5432/postgres?sslmode=disable
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
            path: "**/-failed-*"
